### ISSUE TITLE
For loop for pasting words

### ISSUE THREAD

**Issue by PaoloAmantini** [DataAccess2020/general-info#11]
@DeAngelisA @n-oise @FCatalfamo @EricaRavarelli @AlbaProficuo @AntonioAlaia @maria-ascolese 
Hello, I'm having troubles with the "for loop" ` i <- 1
for(i in 1:74){
  links1$link <- c(stri_paste(api_link,topic[i, 1],".json"))
  links1$link[[nrow+1]] <- links1$link
}` row 97. It doesn't paste all the words I need but just the first. Can any one help me to figure out a solution?

**Comment by FCatalfamo** [comment]
:tada: I will try

**Comment by PaoloAmantini** [comment]
With @FCatalfamo and @n-oise, we fixed the first loop. I still have  this loop 
``` {r} 
 i <- 1
for(i in 1:nrow(links)){
  result <- RCurl::getURL(links1$links,
                          httpheader = c(links1$key))
  cat(result)
  Sys.sleep(1)
}
```
that is not working properly. 😔
