### ISSUE TITLE
It keeps giving me an error

### ISSUE THREAD

**Issue by PaoloAmantini** [DataAccess2020/general-info#12]
@DeAngelisA @n-oise @FCatalfamo @EricaRavarelli @AntonioAlaia @maria-ascolese @AlbaProficuo 
```
i <- 1
for(i in 1:nrow(query)){
 result <- RCurl::getURL(query$r_link,
                        httpheader = c(query$key))
cat(result)
Sys.sleep(1)
}
```
It downloads the data but then doesn't assign it to "result" and gives as Error: unable to establish connection with R session when executing `console_imput`.

**Comment by maria-ascolese** [comment]
@PaoloAmantini I've never had such error so I'm not sure, but I looked it up and found this [list of suggestions](https://www.programmingr.com/r-error-messages/unable-to-establish-connection-with-r-session/#:~:text=One%20of%20the%20things%20that,Rscript%20file%20trying%20to%20autosave.), plus this [similar discussion](https://community.rstudio.com/t/rstudio-error-unable-to-establish-connection-with-r-session/58759/2). Mind that the `console_input` error seems to be related to RStudio trying to save stuff, so check out those suggestions in particular

**Comment by PaoloAmantini** [comment]
@maria-ascolese I already tried, now i'm dividing again the for loop
