### ISSUE TITLE
Table votes

### ISSUE THREAD

**Issue by FCatalfamo** [DataAccess2020/general-info#6]
@AlbaProficuo @AntonioAlaia @maria-ascolese @EricaRavarelli @PaoloAmantini @n-oise 
🚨 Non riesco a effettuare la richiesta delle API dal sito ProPublica
Se qualcuno volesse fare un tentativo i pacchetti sono nel file 01_preparation e i dati nel file 05 votes table
Se necessitate dell'API key ve la mando in privato

**Comment by DeAngelisA** [comment]
@FCatalfamo : non credo che inviare la API key rispetti i termini della API... Piuttosto: che status http ricevi? Hai altre informazioni sul messaggio di errore? Puoi mettere gli la API call?

**Comment by FCatalfamo** [comment]
> @FCatalfamo : non credo che inviare la API key rispetti i termini della API... 

Lo so, era per comodità se qualcuno avesse potuto aiutarmi

**Comment by AntonioAlaia** [comment]
Fatto, ti invio .json files asap 🚀
