### ISSUE TITLE
Capstone output

### ISSUE THREAD

**Issue by Nico-Casarin** [DataAccess2020/general-info#7]
@DeAngelisA Possiamo usare come output il formato .pdf al posto di .html? 
Se possibile, per questioni tipografiche, vorrei utilizzare latex come intermedio al posto di markdown. Pdf sarebbe quindi un output più comodo.

**Comment by DeAngelisA** [comment]
@n-oise : certamente, nessun problema. I due formati sono grosso modo equivalenti, ma compilare in .pdf richiede l'istallazione di \Latex. Oggi è anche disponibile tramite l'istallazione di un pacchetto R ([tinytex](https://bookdown.org/yihui/rmarkdown/installation.html#installation)).

**Comment by Nico-Casarin** [comment]
Perfetto! Grazie mille 😁
