### ISSUE TITLE
IBM Personality Insight

### ISSUE THREAD

**Issue by Nico-Casarin** [DataAccess2020/general-info#9]
[**TO** @PaoloAmantini @FCatalfamo @EricaRavarelli @AlbaProficuo @maria-ascolese @AntonioAlaia]:
Qualcuno ha provato ad usare queste API? Sto avendo **seri** problemi ad iscrivermi... mi da sempre errori in fase di registrazione.
Sono io o sono loro?

---
[**TO** @DeAngelisA]:
Cercando *IBM Personality Insight* trovo [questo portale](https://www.ibm.com/it-it/cloud/watson-natural-language-understanding), è giusto? Non trovo molte informazioni usando la chiave di ricerca riportata sul Sillabus. 

Grazie a tutti 😁

**Comment by maria-ascolese** [comment]
Io ho contattato giusto ieri l'assistenza IBM, da quel che mi hanno detto Personality Insights è soprattutto usato per il customer care nell'analisi delle chat con clienti. Se devi fare analisi di speech/text in generale, come me, ti consiglio il Watson Natural Language Understanding. Comunque, per entrambe c'è un periodo di 30 giorni di prova (inizia quando ti iscrivi al Cloud)

**Comment by Nico-Casarin** [comment]
@maria-ascolese, ma tu sei riuscita ad iscriverti? Ho dovuto provare varie volte il processo perché mi dava continui errori... ora che sono riuscito mi chiede, giustamente, di fare l'upgrade dell'account inserendo la Carta di credito (con addebito 0.00). Metto i dati, mi chiede l'autorizzazione sull'homebanking ma poi mi da errore e mi butta fuori dall'account Cloud IBM..

**Comment by maria-ascolese** [comment]
Io in realtà ero già iscritta, e mi è scaduto un paio di giorni fa il periodo di prova. Quando l'ho fatto il mese scorso non ho dovuto inserire niente del genere, riprovo stasera e ti dico 🧐

**Comment by Nico-Casarin** [comment]
@maria-ascolese, grazie!

**Comment by maria-ascolese** [comment]
Mi sono appena registrata [da qui](https://cloud.ibm.com/registration/trial) e sembra andare tutto bene ora. Ho anche regolarmente accesso alle api di Watson. Fammi sapere come va!

**Comment by Nico-Casarin** [comment]
Mmm, funziona perfettamente con questo link. 
Non so come mai ma grazie! 😁

**Comment by DeAngelisA** [comment]
Fantastico, bravissimi!
